
server:
  port: ${PORT:8100}
  compression:
    enabled: true
  #DATABASE
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bulletinbrd
    username: postgres
    password: pass
  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update