
server:
  port: ${PORT:8100}
  compression:
    enabled: true
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
      #dd
  #DATABASE
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-91-223-99.compute-1.amazonaws.com/detuo7918edvls
    username: pyqkoyyweanwcj
    password: bc974b2b0b04261162799d77e3ff5847ebbf9c1d140e479696307e95d025bbda
  #    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/newboard
#    username: postgres
#    password: pass
  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update