
server:
  port: ${PORT:8100}
  compression:
    enabled: true
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
      #dd
  #DATABASE
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://ec2-3-213-66-35.compute-1.amazonaws.com:5432/d6j51q16lptujf
    username: postgres
    password: pass
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/newboard
#    username: postgres
#    password: pass
  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update